# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 260f103923a1d30c69cfca1ea373f08c3bd9e232ae901ed272fa96e3ee0e740af4e72ac5467bbb1e711b0713b4e21afe0d68de3ad9e76b1ea84716adfe0bc4f7

test:
  secret_key_base: ecc15aa02d5096e0783b2fbaae65536ec387edb89916ac453e5dd2bc65b0b4aea22c3138a7ed479b332de84a8b812e59133a1416a37e87929faa54693d2e1067

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
