# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80ee7f72bb29ad80985c7f8b74875bc6b052cc832879ed7b86679f7401eafef56dbc1fc69664cfed798123209d8c2114c53e993e027898a1f5e2bac4763052d2

test:
  secret_key_base: d7a9851eb255e862fb03801b37a191fd443a1840fca41dd157f5d5b560a3c9b64730f804f8de410b04fbc209376ccc7399c0f6fb801fc91866a57101b1911106

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
