# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8acf0f9f17df93cd845a213b5f16cb6fe73d956b73b86ab09166bba1f2679360de30860b6eb5f1ae438d6cc153a904e1e94cf7e93bdb23a608449afd7ff0f308

test:
  secret_key_base: 9ae6b60d333a6533d7fee4d1cc8b57ef3be150aa599d2bb7f80f136de7e2058a4a54eacebc45ab10f50c5b2d32aab81a8849f1644fa878c3595efc2cc54985f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
